const wdb = [
    {
      headingOne: "Experience setting up Git: ",
      oneParagraphOne:"I have set up and briefly used GitHub prior to this course. I have taken the opportunity to review the website, as after creating an account, I have made use of GitHub desktop on a more frequent basis than the actual website. I noticed some beta features on the website, that are not present on the desktop software such as a “trending repositories” and a “recommended for you” section, which struck me as particularly interesting, because to me these seem like features on a social media platform, rather than a website that is used more so in a working/studying context.",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "Reflection on weekly readings",
      twoParagraphOne:"“As we may think” is a piece that is set more in reality, touching on the development of technology, primarily the evolution of technology responsible for creating and storing information. It speaks of the “memex”, a tool that closely mirrors some functionality that the internet also has (mainly that it served as a catalogue for pre-existing information). I think that the internet is becoming steadily more essential in our daily lives, as the retrieval of information is necessary for many of our daily tasks. It is also worth noting, however, that the longer the internet stays relevant, the more information is stockpiled in the same place. This can be seen as both a good thing and a bad thing. The collection and retrieval of information in one place can be seen as quite convenient. In contrast, with the amount of information on the internet, the reliability thereof becomes difficult to gauge.",
      twoParagraphTwo:"“The Library of Babel” was a fictional metaphorical piece, which I interpreted as a warning of overabundance of information (like the internet is today). I think that it is true that we are oversaturated with information – similar to the previous reading. Perhaps it is part of our responsibility as future web developers to present information to people in a way that is not overwhelming?",
      twoParagraphThree:"",
      headingThree: "Goals for the course",
      threeParagraphOne:"One of my goals for this course is to try to work consistently through the course material. I would also like to further my technical ability in coding, in order to make functional websites, and understand the theoretical elements that make websites appealing, ultimately combining the two. I'm also interested in learning what our responsibilities are regarding what we put out onto the internet.",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },
    {
      headingOne: "Experience starting with HTML: ",
      oneParagraphOne:" Starting to work with HTML was a fun experience. My favourite thing I learned this week was how easy it is to add media to a website. All I have to do is move the media to the folder that I am working in, and add it with the corresponding element, referencing the filename. This will be important for me to know, as I intend to to add pictures and videos to my websites. I would also like to make navigating around and between pages of the website quick and easy. This is possible in a similar way.",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "Reflection on Readings: ",
      twoParagraphOne:"I completed the Bruce Larson reading, “Why you should Choose HTML5 article over section”. One thing that I found interesting from this reading (that was further emphasized in the technical lecture for the week), is the fact that, although two things might appear the same visually, if they are implemented in different ways, they can be functionally different. Examples include the <strong> and <b> tags, both of which make the text which they surround bold. Under the hood, however they function differently and can make differences in the discoverability and usability of my websites. Similarly, the reading also mentions that, wrapping an h1 element in a section element, can change the size of the h1 text. Visually, this is different, but functionally it is still the same. This would be a example of bad semantic markup.",
      twoParagraphTwo:"I also watched the video “How A Screen Reader User Accesses The Web: A Smashing Video”. This was eye-opening to me, because I’ve never thought of the fact that some people have to access the internet in a non-visual way. It makes sense that screen readers exist, as a manner of including people who would struggle to use technology without tools to make it possible. This video highlights the importance of using HTML properly in order to make websites easily comprehendible for everyone, despite context that might only be relevant for some people to understand what is going on. A good example of this, as mentioned in the “Why you should Choose HTML5 article over section”, is the fact that there is a quick summary of the web page at the top of the page. Without context, the writing from the summary could flow into the body of writing, which could be confusing for someone who cannot see the visual divider separating the summary from the start of the article.",
      twoParagraphThree:"",
      headingThree: "Reflection on Internet Histories: ",
      threeParagraphOne:"We also covered some of the history of the internet this week. I have many fond memories of playing browser games on the MiniClips website, a website that made significant usage of Flash. It has also been interesting to see how the internet has been monopolized throughout its life cycle.",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },
    {
      headingOne: "Developments of website development: ",
      oneParagraphOne:"This week we were introduced to CSS, the tool that it is primarily responsible for styling our websites. Last week, while I was trying to create a wireframe, I struggled to create a vision for myself. This is largely because I was unsure of what would even be possible. After some exposure to CSS, however, it has been somewhat easier to imagine my website. From what I’ve seen, a fair amount of CSS seems to be about experimenting with values until the perfect ones are found. This will not change how I approach developing my wireframe. Now that I know what is possible, I will use CSS as an opportunity to refine my website, into exactly what I want it to be (with the wireframe being a rough idea).",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "The reading, lecture, and how it ties into UI and UX: ",
      twoParagraphOne:"Mailloux’s Convention and Context had some insight that I think is valuable when considering how we choose to design our websites. Convention can be defined as commonly accepted practice within some context (Mailloux 1983: 399). In the context of UI and UX for web development, convention plays an important role for how we design websites for people to use. Feedback and responsiveness are conventional, because it tells the user that the actions that they are wanting to complete are understood. We make use of pre-existing website structures (even if we aren’t necessarily aware of it) because they are familiar and make for an easy experience to a user who might not have ever visited our websites before. An example of this is search bars, which commonly appear in the header of websites. It would be unconventional to hide a search bar on the footer of a page because most people wouldn’t think to look for it there.",
      twoParagraphTwo:"It is important to acknowledge when convention must be used in a sparing manner, as convention can limit innovation. While it helps to be familiar, it is equally important to think outside the box and push the boundaries to create new conventions to be used in the future/create experiences that are unique and memorable. The context of web development is changing (more companies have been using their websites as a primary source of traffic since COVID-19), and so consequently convention will change as well (Mailloux, 1983: 404). Conventions are tools that can help us as designers to create intuitive digital experiences for others.",
      twoParagraphThree:"",
      headingThree: "Supplementary material and why I think it’s useful: ",
      threeParagraphOne:"I usually find that having multiple perspectives of the same work is beneficial. This course is no exception to that. I find that, if in the technical lectures, if there are concepts that I do not understand, it is sometimes worth going through the corresponding supplementary material. When an unfamiliar concept is given a fresh explanation, I find that I am more likely to absorb it the second time around. Although it is slightly more time consuming to approach understanding some topics in this way, I find that it is worth it in the end because my understanding of the topics on a whole is generally better.",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"Mailloux, S., 1983. Convention and context. New Literary History, 14(2), pp.399-407.",
      referenceTwo:"",
    },    
    {
      headingOne: "Website progress: ",
      oneParagraphOne:"My website has seen some development this week, following last week’s introduction to UI and UX. I have a fairly confident idea of how I want some parts of it to look, but other parts are still relatively undefined. I have put some work into developing the home screen of my website, from my wireframe. Most of this work, however, I have used as an opportunity for me to get more familiar with CSS and using proper semantic markup with HTML. I’ve found that it is quite difficult to achieve “neat” CSS, perhaps someone has some advice that I may not know of to make my CSS look a bit neater?",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "Reading vs Wireframe: ",
      twoParagraphOne:" This week’s reading contained some tips to create a more effective user interface. One of the tips involves being aware of who the audience of the website will be (Uxpin 2020: 1). The purpose of our website, is to act as a portfolio for us to showcase ourselves, and thus it is safe to assume that our target audiences would consist of potential employers. It also struck me as useful to read that it shouldn’t take more than 3 clicks to find information (Uxpin 2020: 4).",
      twoParagraphTwo:"I can say that I was aware of some of the principles mentioned in the reading, but not as many of them as I would have liked to. I took the opportunity to try to review some portfolio websites to see how some if some of the tips have been followed. For anyone interested in software engineering, I found the examples given on this blog to be useful to go through: https://careerfoundry.com/en/blog/web-development/software-engineer-portfolio/Links to an external site.",
      twoParagraphThree:"",
      headingThree: "UI and Interactivity: ",
      threeParagraphOne:" The interface of our website will be the factor that combines UI with interactivity for our website. Thus it is important that the interface is built in such a way that it is effective. We can use methods of UI design such as giving the user feedback, to know that their interaction with the website is acknowledged by the website (Uxpin 2020: 4).",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"Hannah, J. 2023. The Ultimate Software Engineer Portfolio Guide (With 24 Examples). software-engineer-portfolio. Online. careerfoundry.comLinks to an external site.. 20 March 2023.",
      referenceTwo:"Uxpin. (2020). The Basic Principles of User Interface Design. The Basic Principles of User Interface Design (uxpin.comLinks to an external site.). 19 March 2023.",
    },    
    {
      headingOne: "Website Progress:",
      oneParagraphOne:"This week I spent some time considering the colour palette I want my website to have. While I understand that this is an opportunity to express myself in a unique way, I think it is important to remember that this website’s purpose is to showcase a portfolio of our work to potential employers. With this in mind, I have chosen to keep my website image free where I can afford to, and use clean, professional colours. I have chosen to use dark blues, grey and orange, although this is subject to change.",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "Colour Theory:",
      twoParagraphOne:" This week I spent some time researching colour theory and how it applies to websites. Colour is an important factor for us to consider because it helps us communicate the state of the website to the user. It is useful to keep the colour wheel in mind when picking colours as this can be a useful tool in making effective choices. We can use complimentary colours (that sit on opposite sides of the colour wheel) to bring focus to specific elements. This is due to the high contrast between complimentary colours. I think I can use this to show the user that something they are hovering over is interactable. I think I will also primarily use a dark blue palette for the majority of my website to give it a harmonious and sophisticated look.",
      twoParagraphTwo:"",
      twoParagraphThree:"",
      headingThree: "Introduction to the Document Object Model (DOM):",
      threeParagraphOne:"This week we were introduced to something called the Document Object Model. This is a useful tool that allows for real time manipulation of our websites. I can imagine that this is something that will be very useful to learn and understand well. I attempted the exercises but I struggled to complete them successfully. I think for the moment, I will be prioritizing the development of my website, but this is something that I want to master so I can use it effectively when it is needed in my website.",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },    
    {
      headingOne: "Website Development: ",
      oneParagraphOne:"This week, I spent some time reconsidering the flow of my website. Originally, I had decided that my website would be one continuous page, with a static header that would direct the user to their desired section, but after some thinking I do not think that was the right idea. I have changed my design, to break my website into different pages that the user can navigate to. This way, the user is not overwhelmed with information immediately upon entering the site.",
      oneParagraphTwo:" While implementing the styling for my Weekly Dev Blog page, I encountered some unintentional styling that I have chosen to keep. The actual content of my weekly dev blog sits inside a section, inside another section, to visually separate each week’s content. The styling I wanted to apply to the outer most section, applied to the inner one to, and the effect is that it looks like the user is being presented with the page from a journal, which I think is visually pleasing. ",
      oneParagraphThree:"",
      headingTwo: "IxD Process: ",
      twoParagraphOne:"This week we had a lecture on interaction design. It was eye opening to see how many things there are to take into consideration with regards to effective design for our website. I think that the idea of building a website in a way that makes it easy for someone who has not seen it before. On a smaller scale too, it makes sense to design sections on pages to function in similar ways. That way, for example, someone who is navigating from my Weekly Dev Blog page to my Design page is able to be familiar with how it works because it functions in a similar way. ",
      twoParagraphTwo:"Event Handling: This week’s practical lecture was a continuation of DOM manipulation stuff. We were exposed to event handling, which is how our website responds to user input. This is done through the use of something called “event listeners” which are used to detect user input. This is something that I can definitely see myself using in my own website (Instead of hard coding things in HTML, such as my Weekly Dev Blog content, it could be possible to use event handling to make some more complex ways to engage with the content), however this will have to happen at a later stage once I can familiarize myself more with how the DOM works better.",
      twoParagraphThree:"",
      headingThree: "",
      threeParagraphOne:"",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },    
    {
      headingOne: "Website development: ",
      oneParagraphOne:" I have been taking the extended project brief into consideration with the continued development of my website. This process has forced me to reconsider the design of some sections of my website. In an effort to clean things up, I have decided to combine some sections (for the sake of reducing the number of options that the user is faced with at a time). This has forced me to rethink the flow of the website, and change my wireframes accordingly. Thankfully the actual implementation of my website is still fairly barebones, so it should not be a great effort to implement the changes I am wanting to make. Since the first assignment has little to no emphasis on aspects of JavaScript, I have prioritized becoming more confident in HTML and CSS. I attempted the DOM manipulation exercises, and although I found them challenging I am not worried at this stage, as I plan to find the time later on to sharpen these skills.",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "IxD process lecture: ",
      twoParagraphOne:"I have taken the flow of my website into consideration. I intend to have a header that stays permanently visible (in desktop mode, at least), as a means for easy navigation for the user. I am attempting to make each of my pages internally familiar, as this will help the user to get used to the format of my website quickly, and I will use external familiarity elements so that the user is given a seamless experience when viewing my website for the first time.",
      twoParagraphTwo:"We want the users of our website to think about the decisions they are making as little as possible, hence the importance of Hick’s Law. I have been trying to find ways to condense the number of decisions that the user can be faced with at one time. In terms of navigation, I have taken this into account by combining similar sections together. This has been done so that initial navigation is less intimidating, and the user is able to increase the specificity of their navigation as they need to.",
      twoParagraphThree:"I intend to use emphasis and dominance to show the user information that they have selected. This will be seen, on the header giving the user a visual indication of which page of the website they are currently on, and on the page in general if they are hovering over/close to something that they can interact with. I will change size and shape, to effectively communicate potential and completed actions.",
      headingThree: "Weekly reading reflection: ",
      threeParagraphOne:"We cannot design in a way that expects the audience to achieve the exact same experience through our design, but we can design in a way that ensures that the audience can use the design to arrive at an individual experience (Hassenzahl & Tractinksy 2006: 95). UX takes the experience of the user into account while HCI is primarily focused on the functionality of the interface. As we take into account the UX aspects of our websites, it is important to consider both the ease of use and effectiveness of our website, as well as the experiences for the user that come as a consequence of engaging with our website.",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"Hassenzahl, M. & Tractinsky, N., 2006. User experience-a research agenda. Behaviour & information technology, 25(2), pp.91-97.",
      referenceTwo:"",
    },    
    {
      headingOne: "Things I think I did right: ",
      oneParagraphOne:"Although I mostly followed my wireframe, some “happy accidents” occurred, that I think improved my website for the better. This meant going slightly off script, but I think helped me to understand that a website is a living document that can be changed and updated at any time. The final product that I am making will probably not look exactly the same as the current iteration of my wireframe.",
      oneParagraphTwo:"One thing that I think I did right, was thinking about the project in a long term scalable way. This assignment had us include 7 weekly dev blog posts. This was a very tedious process with only the use of CSS and HTML. I know from the technical lectures that the use of JavaScript functions would make this process significantly easier, and going forward I plan to implement this in this section to avoid tedious hard coding.One thing that I think I did right, was thinking about the project in a long term scalable way. This assignment had us include 7 weekly dev blog posts. This was a very tedious process with only the use of CSS and HTML. I know from the technical lectures that the use of JavaScript functions would make this process significantly easier, and going forward I plan to implement this in this section to avoid tedious hard coding.",
      oneParagraphThree:"Another thing that I did right was make sure that I had the GitHub repository and GitHub pages sorted out, so that I did not run into any last minute problems with that.",
      headingTwo: "Things I struggled with:",
      twoParagraphOne:"One thing that I struggled with, was gauging how much time little nit-picky things would take to implement. While I found that it was not too difficult to get 85% of the work done, the final 15% took a lot longer than I anticipated, and probably cost me marks in silly places because I was forced to work quickly in order to submit in time. I also found myself spending a lot of time trying to find smart ways to create functionality with CSS, knowing full well that I will probably get rid of this functionality when it comes to the next website submission, because I will be making use of JavaScript. I am proud of the functionality that I managed to implement, but I understand that it is probably largely redundant in the long run.",
      twoParagraphTwo:"",
      twoParagraphThree:"",
      headingThree: "Readings: ",
      threeParagraphOne:"Digital Hegemonies - Countries are more likely to see local content in web browsers, if the countries are wealthier . Less wealthy countries are shown content from wealthier countries over local content. This puts local content in poorer countries at a disadvantage, because it is less likely to be seen, both within the country that it has originated from, and the international stage at large.",
      threeParagraphTwo:"Information Geographies - In general, the Global North has a greater access to technology and information on the internet than the Global South. There is also a discrepancy between the types of technology used in each region, which contributes to the divide between the two.",
      threeParagraphThree:"How this affects my thinking on web dev as a South African - As web developers in the Global South, it is part of our responsibility to increase participation and representation in the digital content we are involved in creating. This could include encouraging South Africans to participate in discussions online, and building websites that are platform compatible for as many people as possible. This will help us to bridge the gap between the global North and South, contributing to a more fair distribution of information.",
      references:"",
      referenceOne:"Ballatore, A., Graham, M. and Sen, S., 2017. Digital hegemonies: the localness of search engine results. Annals of the American Association of Geographers, 107(5), pp.1194-1215.",
      referenceTwo:"Graham, M., De Sabbata, S., & Zook, M.A. (2015). Towards a study of information geograph-ies: (im)mutable augmentations and a mapping of the geographies of information. Geo: Geography and Environment, 2(1), pp.88-105.",
    },    
    {
      headingOne: "Website Development: ",
      oneParagraphOne:"This week, I fixed up some of the things in my website that I noticed needed to change after my submission. I have also taken some time to look at areas that can/need to be improved before the submission of the 3rd assignment. This includes areas where JavaScript functionality will be useful, and general tweaking to make the usage of my website a more enjoyable experience. This will be updated in my wireframes, and will be updated in the design section of my website. I have made separate GitHub branch in my project that will enable me to push my changes without worrying about changing anything about the actual submission for the first assignment. This way, at least I still have version control in case my tinkering breaks anything.",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "Close Reading: ",
      twoParagraphOne:"I looked at “How Geography Shapes - and Is Shaped by - the Internet”, which highlights how adoption of the internet has an impact of costing in three main factors: communication, transportation and searching (Forman & Goldfarb & Greenstein 2018). Depending on the geographical locations of areas, these factors are either beneficial or not.",
      twoParagraphTwo:"For this close reading, I will be focusing on the implications of the internet for consumer behaviour. Consumers in general, benefit from the existence of the internet and the utilization of it for communication, transportation, and searching. Most of the benefits of the internet are shared by consumers in varying densely populated areas.",
      twoParagraphThree:"Distribution costs of certain products (namely, products that can be digitized) has been reduced thanks to the internet. In most cases, products that cannot be distributed digitally, have a lower transport cost than what it would cost the consumer to visit an in-person store to buy the same product. Online stores are also utilized for niche products that are required by isolated individual consumers and minorities, even if the same niche product is offered in an in-person store. Research has shown that a wider catalogue of products can be presented to consumers on websites, than can be presented in physical stores.",
      headingThree: "",
      threeParagraphOne:"Consumers tend to visit online sites for shops that are local to them, due to the fact that “consumer tastes are spatially correlated and vary significantly across regions” (Forman & Goldfarb & Greenstein 2018) Additionally, there are regulatory reasons that encourage consumers to visit local store websites.",
      threeParagraphTwo:"The COVID-19 pandemic was an eye-opening experience that showed a boom in online purchasing. Businesses such as Checkers have services that allow consumers in South Africa to purchase groceries without the need to leave their homes. This is an example of effective use of the internet to cut costs and make the shopping experience more convenient to consumers.",
      threeParagraphThree:"",
      references:"",
      referenceOne:"Forman, C & Goldfarb A. & Greenstein, S. 2018. How geography shapes-and is shaped by-the internet. The new Oxford handbook of economic geography, 269.",
      referenceTwo:"",
    },    
    {
      headingOne: "Website Development: ",
      oneParagraphOne:"There were a number of things I would have liked to try to implement in my website for the first assignment, but I was unable to. This mostly consists of JavaScript, which will help way to bring information to the user, instead of the other way round. The technical lecture we had this week, focusing on more CSS, also highlighted some avenues that I had not considered previously.",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "Reading",
      twoParagraphOne:"The reading introduces the topic of algorithmic coloniality - the existence of power dynamics in technology that closely resembles colonial characteristics. As colonialism is the extraction and exploitation of real-world places, algorithmic coloniality is extraction and exploitation of knowledge systems and digital structures. We must be aware that colonial characteristics continue to persist in topics related to AI.",
      twoParagraphTwo:"Such characteristics contribute to biases and oppression, known as Algorithmic oppression. Algorithmic oppression is the unjust equality of social groups through data-driven systems. These systems are intended to be unbiased, and driven by evidence, but according to research, they contain social biases, which in turn repeat historical injustices. AI is used increasingly to help make decisions.",
      twoParagraphThree:"The reading also suggests the idea of decolonial AI, which can be used to challenge colonialism and promote social justice. It is suggested that we can better understand and communicate . As AI continues to develop, it is necessary for a greater inclusion and diversity of information to be used in order to reach a wider audience in meaningful ways.",
      headingThree: "",
      threeParagraphOne:"",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },    
    {
      headingOne: "",
      oneParagraphOne:"",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "",
      twoParagraphOne:"",
      twoParagraphTwo:"",
      twoParagraphThree:"",
      headingThree: "",
      threeParagraphOne:"",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },    
    {
      headingOne: "",
      oneParagraphOne:"",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "",
      twoParagraphOne:"",
      twoParagraphTwo:"",
      twoParagraphThree:"",
      headingThree: "",
      threeParagraphOne:"",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },    
    {
      headingOne: "",
      oneParagraphOne:"",
      oneParagraphTwo:"",
      oneParagraphThree:"",
      headingTwo: "",
      twoParagraphOne:"",
      twoParagraphTwo:"",
      twoParagraphThree:"",
      headingThree: "",
      threeParagraphOne:"",
      threeParagraphTwo:"",
      threeParagraphThree:"",
      references:"",
      referenceOne:"",
      referenceTwo:"",
    },
  ];